import os, sys, re, subprocess
from github import Github

GH_TOKEN = os.environ["GH_TOKEN"]
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
REPO_NAME = os.environ.get("REPO_NAME", "mrtwister99-png/android-app-main")
AGENT_LABEL = os.environ.get("AGENT_LABEL", "android-nav")
print(f"START {AGENT_LABEL} on {REPO_NAME}")

# NOVY SDK - google.genai misto deprecated generativeai
try:
    from google import genai
    client = genai.Client(api_key=GEMINI_API_KEY)
    USE_NEW = True
    print("Using google.genai SDK")
except ImportError:
    import google.generativeai as genai
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel("gemini-2.0-flash")
    USE_NEW = False
    print("Using legacy generativeai SDK")

from github import Github
g = Github(GH_TOKEN)
repo = g.get_repo(REPO_NAME)

issues = list(repo.get_issues(state="open", labels=[AGENT_LABEL]))
if not issues:
    print(f"No open issues with label {AGENT_LABEL} - exit OK")
    sys.exit(0)

issue = issues[0]
print(f"Processing #{issue.number} {issue.title}")

structure=[]
for root,dirs,files in os.walk("main/app/src"):
    if "build" in root: continue
    for f in files[:25]:
        if f.endswith(".kt"):
            structure.append(os.path.join(root,f).replace("\\","/"))

prompt=f"""You are Kotlin Android expert SDK 37 package com.example.newapp
ISSUE #{issue.number}: {issue.title}
BODY: {issue.body}
ROLE: {AGENT_LABEL}
Existing files: {chr(10).join(structure[:35])}
Task: Output max 3 files in format:
FILE: app/src/main/java/com/example/newapp/xxx.kt
```kotlin
code
```
Keep package, fix issue.
"""

if USE_NEW:
    resp = client.models.generate_content(model="gemini-2.0-flash", contents=prompt)
    text = resp.text
else:
    resp = model.generate_content(prompt)
    text = resp.text

print(text[:4000])

pattern=re.compile(r'FILE:\s*(.+?)\n```(?:kotlin)?\n(.*?)\n```', re.DOTALL)
matches=pattern.findall(text)
if not matches:
    print("No FILE matches found")
    sys.exit(1)

os.chdir("main")
subprocess.run(["git","config","user.name","Loyo Bot"], check=True)
subprocess.run(["git","config","user.email","bot@loyo.cz"], check=True)
branch=f"feature/{issue.number}-{AGENT_LABEL}"
subprocess.run(["git","branch","-D",branch], check=False)
subprocess.run(["git","checkout","-b",branch], check=True)

for path,content in matches:
    path=path.strip().lstrip("/")
    # ensure inside app/src
    if not path.startswith("app/src"): 
        path = f"app/src/main/java/com/example/newapp/{os.path.basename(path)}"
    full=os.path.join(os.getcwd(), path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    open(full,"w",encoding="utf-8").write(content)
    print(f"Wrote {path}")

subprocess.run(["git","add","-A"], check=True)
subprocess.run(["git","commit","-m",f"[{AGENT_LABEL}] #{issue.number} {issue.title}"], check=True)
remote=f"https://x-access-token:{GH_TOKEN}@github.com/{REPO_NAME}.git"
subprocess.run(["git","push","-f",remote,branch], check=True)

pr=repo.create_pull(title=f"[{AGENT_LABEL}] {issue.title} (#{issue.number})", body=f"Closes #{issue.number}\n\nAuto-generated by {AGENT_LABEL} agent using gemini-2.0-flash", head=branch, base="main")
issue.create_comment(f"PR created: #{pr.number} -> {pr.html_url}")
print(f"PR {pr.number} created OK")
